# Generated by Django 4.1.6 on 2023-02-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskname",
            name="date",
            field=models.DateField(default="1998-01-01"),
            preserve_default=False,
        ),
    ]
