# Generated by Django 4.2.1 on 2023-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="male", max_length=10
            ),
        ),
    ]
