# Generated by Django 4.2.1 on 2023-05-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0002_alter_person_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="wikipedia_url",
            field=models.URLField(default=0.00045004500450045),
            preserve_default=False,
        ),
    ]
