# Generated by Django 4.2.1 on 2023-05-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0003_branch_wikipedia_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="wikipedia_url",
        ),
        migrations.AddField(
            model_name="district",
            name="wikipedia_url",
            field=models.URLField(default=0.0009000900090009),
            preserve_default=False,
        ),
    ]
