# Generated by Django 4.2.1 on 2023-05-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0002_rename_date_person_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="desc",
            field=models.TextField(default=0.0004945598417408506),
            preserve_default=False,
        ),
    ]
