# Generated by Django 4.2.1 on 2023-05-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0003_district_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="slug",
            field=models.SlugField(
                default=0.0004945598417408506, max_length=250, unique=True
            ),
            preserve_default=False,
        ),
    ]
