# Generated by Django 4.2.1 on 2023-05-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0004_district_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="district",
            name="slug",
        ),
    ]
