# Generated by Django 4.1.6 on 2023-02-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="img",
            field=models.ImageField(default="pics", upload_to="gallery"),
            preserve_default=False,
        ),
    ]
